package com.epam.codereview.support;

import org.springframework.ai.chat.metadata.ChatResponseMetadata;
import org.springframework.ai.chat.metadata.Usage;
import org.springframework.ai.chat.model.ChatResponse;

/**
 * LLM token counts exactly as reported by the model provider for one or more chat calls. A call
 * whose provider reports no usage, or reports a count as {@code null}, contributes zero rather
 * than an estimate.
 *
 * @param promptTokens     tokens sent to the model
 * @param completionTokens tokens generated by the model, including any reasoning tokens
 * @param totalTokens      provider-reported total for the call(s)
 */
public record TokenUsage(int promptTokens, int completionTokens, int totalTokens) {

  public static final TokenUsage ZERO = new TokenUsage(0, 0, 0);

  /**
   * @param response a chat response returned by {@code ChatModel#call(Prompt)}
   * @return the usage the provider reported for that single call, or {@link #ZERO} if none
   */
  public static TokenUsage from(ChatResponse response) {
    ChatResponseMetadata metadata = response.getMetadata();
    Usage usage = metadata == null ? null : metadata.getUsage();
    if (usage == null) {
      return ZERO;
    }
    return new TokenUsage(countOrZero(usage.getPromptTokens()),
      countOrZero(usage.getCompletionTokens()), countOrZero(usage.getTotalTokens()));
  }

  /**
   * @return a new instance whose every count is the sum of this and {@code other}'s
   */
  public TokenUsage plus(TokenUsage other) {
    return new TokenUsage(promptTokens + other.promptTokens,
      completionTokens + other.completionTokens, totalTokens + other.totalTokens);
  }

  private static int countOrZero(Integer tokens) {
    return tokens == null ? 0 : tokens;
  }
}
